### ISSUE TITLE
Rename package name or source directory

### ISSUE THREAD

**Issue by MatKie** [gustavochm/SGTPy#2]
Currently the source directory is name 'sgtpy' but the package is named 'SGTPy'. This works on some, like Mac OS and Windows, but not on Linux, where I can only do 'import sgtpy' and not import 'SGTPy' but on Mac OS I can only do 'import SGTPy' but not 'import sgtpy'. 
It's apparently standard to use all lowercase module names get around this, see here:

https://stackoverflow.com/questions/43130046/capitalization-standards-in-importing-in-python

I currently get around that issue by renaming my source folder on Linux (which is not ideal, but works), but long term for other people to use it would be easier to use the standard of all lowercase package naming.

**Comment by gustavochm** [comment]
Dear Matthias,

Thanks for reporting this issue. I wasn't aware of the modules's name standard.
I will update the folder name, setup file and examples.

Gustavo

**Comment by gustavochm** [comment]
Dear Matthias,

I just updated the repo to v0.0.13. The name of the package has changed to `sgtpy`.  I also added some other interesting capabilities as temperature dependent kij, lij, cii and betaij!

Hope you will find these useful!

Gustavo
