### ISSUE TITLE
Misnomer HCO- in database

### ISSUE THREAD

**Issue by Kycilak** [gustavochm/sgtpy#4]
In saftgamma_database.xlsx, sheet groups, row 53 there is a group named HCO- but it seems to me it was meant to be formate HCOO-.

**Comment by gustavochm** [comment]
Dear Kycilak,

Thanks for noticing this error. Checking at the [original database](https://pubs.acs.org/doi/10.1021/acs.jced.0c00746), the name of the group was HCO3-.
I updated the excel file in GitHub and shortly will update the package in PyPI. 

Also, please consider that the Ion and Born contributions are not implemented yet in sgtpy, so this can lead to wrong results when using charged groups.

Kind regards,
Gustavo
